# Generated by Django 4.1.6 on 2023-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheeltunes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
