# Generated by Django 4.1.6 on 2023-02-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheeltunes_app', '0003_remove_song_duration_remove_song_file_song_playable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='playable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.IntegerField(default=50),
        ),
    ]
