# Generated by Django 4.1.6 on 2023-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheeltunes_app', '0005_song_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(default=40)),
                ('speed', models.IntegerField(default=0)),
                ('background_noise', models.IntegerField(default=20)),
            ],
        ),
    ]
