# Generated by Django 4.1.3 on 2023-02-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheeltunes_app', '0006_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='mood',
            field=models.CharField(default='', max_length=100),
        ),
    ]
